<?php

########################################################################
# Extension Manager/Repository config file for ext: "cicevents"
#
# Auto generated by Extension Builder 2012-03-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CIC Events',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Peter Soots',
	'author_email' => 'peter@castironcoding.com',
	'author_company' => 'Cast Iron Coding',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.4.1',
			'fluid' => '1.4.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>